apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-quickstart-pv
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: 
  capacity: 
    storage: 1Gi
  claimRef:
    name: elasticsearch-data-quickstart-es-default-0
    namespace: default
  local:
    path: /mnt/elasticsearch-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rockykubes01
          - rocky-kubes02
          - rockykubes03
